import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

export default function Home() {
  return (
    <>
      <Head>
        <title>AITI | Ali Inovasi Teknologi Indonesia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="shortcut icon"
          type="image/x-icon"
          href="assets/media/favicon.png"
        />
      </Head>
      <>
        {/*[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  	<![endif]*/}
        <a href="#main-wrapper" id="backto-top" className="back-to-top">
          <i className="far fa-angle-double-up" />
        </a>
        {/* Preloader Start Here */}
        <div id="preloader" />
        {/* Preloader End Here */}
        <div className="my_switcher d-none d-lg-block">
          <ul>
            <li title="Light Mode">
              <a
                // href="javascript:void(0)"
                className="setColor light"
                data-theme="light"
              >
                <i className="fal fa-lightbulb-on" />
              </a>
            </li>
            <li title="Dark Mode">
              <a
                href="javascript:void(0)"
                className="setColor dark"
                data-theme="dark"
              >
                <i className="fas fa-moon" />
              </a>
            </li>
          </ul>
        </div>
        <div id="main-wrapper" className="main-wrapper">
          {/*=====================================*/}
          {/*=        Header Area Start       	=*/}
          {/*=====================================*/}
          <header className="header axil-header header-style-1">
            <div id="axil-sticky-placeholder" />
            <div className="axil-mainmenu">
              <div className="container">
                <div className="header-navbar">
                  <div className="header-logo">
                    <a href="index-1.html">
                      <img
                        className="light-version-logo"
                        src="assets/media/logo.svg"
                        alt="logo"
                      />
                    </a>
                    <a href="index-1.html">
                      <img
                        className="dark-version-logo"
                        src="assets/media/logo-3.svg"
                        alt="logo"
                      />
                    </a>
                    <a href="index-1.html">
                      <img
                        className="sticky-logo"
                        src="assets/media/logo-2.svg"
                        alt="logo"
                      />
                    </a>
                  </div>
                  <div className="header-main-nav">
                    {/* Start Mainmanu Nav */}
                    <nav className="mainmenu-nav" id="mobilemenu-popup">
                      <div className="d-block d-lg-none">
                        <div className="mobile-nav-header">
                          <div className="mobile-nav-logo">
                            <a href="index-1.html">
                              <img
                                className="light-mode"
                                src="assets/media/logo-2.svg"
                                alt="Site Logo"
                              />
                              <img
                                className="dark-mode"
                                src="assets/media/logo-3.svg"
                                alt="Site Logo"
                              />
                            </a>
                          </div>
                          <button
                            className="mobile-menu-close"
                            data-bs-dismiss="offcanvas"
                          >
                            <i className="fas fa-times" />
                          </button>
                        </div>
                      </div>
                      <ul className="mainmenu">
                        <li className="menu-item-has-children">
                          <a href="javascript:void(0);">Digital Agency</a>
                          <ul className="axil-submenu">
                            <li>
                              <a href="index-1.html">Digital Agency</a>
                            </li>
                            <li>
                              <a href="index-2.html">Creative Agency</a>
                            </li>
                            <li>
                              <a href="index-3.html">Personal Portfolio</a>
                            </li>
                            <li>
                              <a href="index-4.html">Home Startup</a>
                            </li>
                            <li>
                              <a href="index-5.html">Corporate Agency</a>
                            </li>
                          </ul>
                        </li>
                        <li className="menu-item-has-children">
                          <a href="javascript:void(0);">Services</a>
                          <ul className="axil-submenu">
                            <li>
                              <a href="service.html">Service</a>
                            </li>
                            <li>
                              <a href="service-2.html">Service Two</a>
                            </li>
                            <li>
                              <a href="service-design.html">Service Details</a>
                            </li>
                          </ul>
                        </li>
                        <li className="menu-item-has-children">
                          <a href="javascript:void(0);">Portfolio</a>
                          <ul className="axil-submenu">
                            <li>
                              <a href="portfolio.html">Two Column</a>
                            </li>
                            <li>
                              <a href="portfolio-2.html">Three Column</a>
                            </li>
                            <li>
                              <a href="portfolio-3.html">Four Column</a>
                            </li>
                            <li>
                              <a href="portfolio-4.html">Three Column Width</a>
                            </li>
                            <li>
                              <a href="portfolio-5.html">Four Column Width</a>
                            </li>
                            <li>
                              <a href="single-portfolio.html">
                                Portfolio Details
                              </a>
                            </li>
                          </ul>
                        </li>
                        <li className="menu-item-has-children">
                          <a href="javascript:void(0);">Pages</a>
                          <ul className="axil-submenu">
                            <li>
                              <a href="about-us.html">About Us</a>
                            </li>
                            <li>
                              <a href="our-office.html">Our Office</a>
                            </li>
                            <li>
                              <a href="case-study.html">Case Study</a>
                            </li>
                            <li>
                              <a href="single-case-study.html">
                                Case Study Details
                              </a>
                            </li>
                            <li>
                              <a href="team.html">Team</a>
                            </li>
                            <li>
                              <a href="single-team.html">Team Details</a>
                            </li>
                            <li>
                              <a href="our-clients.html">Our Clients</a>
                            </li>
                            <li>
                              <a href="testimonial.html">Testimonial</a>
                            </li>
                            <li>
                              <a href="pricing-table.html">Pricing Table</a>
                            </li>
                            <li>
                              <a href="typography.html">Typography</a>
                            </li>
                            <li>
                              <a href="404.html">404 Page</a>
                            </li>
                            <li>
                              <a href="coming-soon.html">Coming Soon</a>
                            </li>
                          </ul>
                        </li>
                        <li className="menu-item-has-children">
                          <a href="javascript:void(0);">Blog</a>
                          <ul className="axil-submenu">
                            <li>
                              <a href="blog.html">Blog</a>
                            </li>
                            <li>
                              <a href="single-blog.html">Standard Post</a>
                            </li>
                            <li>
                              <a href="single-blog-gallery.html">
                                Gallery Post
                              </a>
                            </li>
                            <li>
                              <a href="single-blog-video.html">Video Post</a>
                            </li>
                            <li>
                              <a href="single-blog-audio.html">Audio Post</a>
                            </li>
                            <li>
                              <a href="single-blog-quote.html">Quote Post</a>
                            </li>
                          </ul>
                        </li>
                        <li>
                          <a href="contact.html">Contact</a>
                        </li>
                      </ul>
                    </nav>
                    {/* End Mainmanu Nav */}
                  </div>
                  <div className="header-action">
                    <ul className="list-unstyled">
                      <li className="sidemenu-btn d-lg-block d-none">
                        <button
                          className="btn-wrap"
                          data-bs-toggle="offcanvas"
                          data-bs-target="#offcanvasMenuRight"
                        >
                          <span />
                          <span />
                          <span />
                        </button>
                      </li>
                      <li className="mobile-menu-btn sidemenu-btn d-lg-none d-block">
                        <button
                          className="btn-wrap"
                          data-bs-toggle="offcanvas"
                          data-bs-target="#mobilemenu-popup"
                        >
                          <span />
                          <span />
                          <span />
                        </button>
                      </li>
                      <li className="my_switcher d-block d-lg-none">
                        <ul>
                          <li title="Light Mode">
                            <a
                              href="javascript:void(0)"
                              className="setColor light"
                              data-theme="light"
                            >
                              <i className="fal fa-lightbulb-on" />
                            </a>
                          </li>
                          <li title="Dark Mode">
                            <a
                              href="javascript:void(0)"
                              className="setColor dark"
                              data-theme="dark"
                            >
                              <i className="fas fa-moon" />
                            </a>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </header>
          {/*=====================================*/}
          {/*=        Banner Area Start         =*/}
          {/*=====================================*/}
          <section className="banner banner-style-1">
            <div className="container">
              <div className="row align-items-center">
                <div className="col-lg-6">
                  <div
                    className="banner-content"
                    data-sal="slide-up"
                    data-sal-duration={1000}
                    data-sal-delay={100}
                  >
                    <h1 className="title">Digital product design agency</h1>
                    <span className="subtitle">
                      Create live segments and target the right people for
                      messages based on their behaviors.
                    </span>
                    <a
                      href="contact.html"
                      className="axil-btn btn-fill-primary btn-large"
                    >
                      Get Started
                    </a>
                  </div>
                </div>
                <div className="col-lg-6">
                  <div className="banner-thumbnail">
                    <div
                      className="large-thumb"
                      data-sal="zoom-in"
                      data-sal-duration={500}
                      data-sal-delay={300}
                    >
                      <img src="assets/media/banner/laptop.png" alt="Laptop" />
                    </div>
                    <ul className="list-unstyled shape-group">
                      <li
                        className="shape shape-1"
                        data-sal="slide-right"
                        data-sal-duration={500}
                        data-sal-delay={400}
                      >
                        <img
                          src="assets/media/banner/marker.png"
                          alt="Marker"
                        />
                      </li>
                      <li
                        className="shape shape-2"
                        data-sal="slide-right"
                        data-sal-duration={500}
                        data-sal-delay={500}
                      >
                        <img
                          src="assets/media/banner/chat-icon.png"
                          alt="Chat"
                        />
                      </li>
                      <li
                        className="shape shape-3"
                        data-sal="slide-left"
                        data-sal-duration={500}
                        data-sal-delay={600}
                      >
                        <img
                          src="assets/media/banner/sticker.png"
                          alt="sticker"
                        />
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <ul className="list-unstyled shape-group-13">
              <li
                className="shape shape-1"
                data-sal="slide-down"
                data-sal-duration={500}
                data-sal-delay={100}
              >
                <img src="assets/media/others/bubble-18.png" alt="Bubble" />
              </li>
              <li
                className="shape shape-2"
                data-sal="slide-left"
                data-sal-duration={500}
                data-sal-delay={200}
              >
                <img src="assets/media/others/bubble-19.png" alt="Bubble" />
              </li>
              <li
                className="shape shape-3"
                data-sal="slide-left"
                data-sal-duration={500}
                data-sal-delay={700}
              >
                <img src="assets/media/others/hand-2.png" alt="Hand" />
              </li>
              <li
                className="shape shape-4"
                data-sal="slide-left"
                data-sal-duration={500}
                data-sal-delay={700}
              >
                <img src="assets/media/others/bubble-14.png" alt="Bubble" />
              </li>
              <li
                className="shape shape-5"
                data-sal="slide-left"
                data-sal-duration={500}
                data-sal-delay={700}
              >
                <img src="assets/media/others/bubble-14.png" alt="Bubble" />
              </li>
            </ul>
          </section>
          {/*=====================================*/}
          {/*=        Service Area Start         =*/}
          {/*=====================================*/}
          <section className="section section-padding-equal bg-color-dark">
            <div className="container">
              <div className="section-heading heading-light-left">
                <span className="subtitle">What We Can Do For You</span>
                <h2 className="title">Services we can help you with</h2>
                <p className="opacity-50">
                  Nulla facilisi. Nullam in magna id dolor blandit rutrum eget
                  vulputate augue sed eu imperdiet.
                </p>
              </div>
              <div className="row">
                <div
                  className="col-lg-4 col-md-6"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={100}
                >
                  <div className="services-grid active">
                    <div className="thumbnail">
                      <img src="assets/media/icon/icon-1.png" alt="icon" />
                    </div>
                    <div className="content">
                      <h5 className="title">
                        {" "}
                        <a href="service-design.html">Design</a>
                      </h5>
                      <p>
                        Simply drag and drop photos and videos into your
                        workspace to automatically add them to your Collab Cloud
                        library.
                      </p>
                      <a href="service-design.html" className="more-btn">
                        Find out more
                      </a>
                    </div>
                  </div>
                </div>
                <div
                  className="col-lg-4 col-md-6"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={200}
                >
                  <div className="services-grid">
                    <div className="thumbnail">
                      <img src="assets/media/icon/icon-2.png" alt="icon" />
                    </div>
                    <div className="content">
                      <h5 className="title">
                        {" "}
                        <a href="service-development.html">Development</a>
                      </h5>
                      <p>
                        Simply drag and drop photos and videos into your
                        workspace to automatically add them to your Collab Cloud
                        library.
                      </p>
                      <a href="service-development.html" className="more-btn">
                        Find out more
                      </a>
                    </div>
                  </div>
                </div>
                <div
                  className="col-lg-4 col-md-6"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={300}
                >
                  <div className="services-grid">
                    <div className="thumbnail">
                      <img src="assets/media/icon/icon-3.png" alt="icon" />
                    </div>
                    <div className="content">
                      <h5 className="title">
                        {" "}
                        <a href="service-marketing.html">Online marketing</a>
                      </h5>
                      <p>
                        Simply drag and drop photos and videos into your
                        workspace to automatically add them to your Collab Cloud
                        library.
                      </p>
                      <a href="service-marketing.html" className="more-btn">
                        Find out more
                      </a>
                    </div>
                  </div>
                </div>
                <div
                  className="col-lg-4 col-md-6"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={100}
                >
                  <div className="services-grid">
                    <div className="thumbnail">
                      <img src="assets/media/icon/icon-4.png" alt="icon" />
                    </div>
                    <div className="content">
                      <h5 className="title">
                        {" "}
                        <a href="service-business.html">Business</a>
                      </h5>
                      <p>
                        Simply drag and drop photos and videos into your
                        workspace to automatically add them to your Collab Cloud
                        library.
                      </p>
                      <a href="service-business.html" className="more-btn">
                        Find out more
                      </a>
                    </div>
                  </div>
                </div>
                <div
                  className="col-lg-4 col-md-6"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={200}
                >
                  <div className="services-grid">
                    <div className="thumbnail">
                      <img src="assets/media/icon/icon-5.png" alt="icon" />
                    </div>
                    <div className="content">
                      <h5 className="title">
                        {" "}
                        <a href="service-technology.html">Technology</a>
                      </h5>
                      <p>
                        Simply drag and drop photos and videos into your
                        workspace to automatically add them to your Collab Cloud
                        library.
                      </p>
                      <a href="service-technology.html" className="more-btn">
                        Find out more
                      </a>
                    </div>
                  </div>
                </div>
                <div
                  className="col-lg-4 col-md-6"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={300}
                >
                  <div className="services-grid">
                    <div className="thumbnail">
                      <img src="assets/media/icon/icon-6.png" alt="icon" />
                    </div>
                    <div className="content">
                      <h5 className="title">
                        {" "}
                        <a href="service-content-strategy.html">
                          Content strategy
                        </a>
                      </h5>
                      <p>
                        Simply drag and drop photos and videos into your
                        workspace to automatically add them to your Collab Cloud
                        library.
                      </p>
                      <a
                        href="service-content-strategy.html"
                        className="more-btn"
                      >
                        Find out more
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <ul className="list-unstyled shape-group-10">
              <li className="shape shape-1">
                <img src="assets/media/others/circle-1.png" alt="Circle" />
              </li>
              <li className="shape shape-2">
                <img src="assets/media/others/line-3.png" alt="Circle" />
              </li>
              <li className="shape shape-3">
                <img src="assets/media/others/bubble-5.png" alt="Circle" />
              </li>
            </ul>
          </section>
          {/*=====================================*/}
          {/*=       Case Study Area Start       =*/}
          {/*=====================================*/}
          <section className="section section-padding-equal case-study-featured-area">
            <div className="container">
              <div className="row">
                <div
                  className="col-xl-5 col-lg-6"
                  data-sal="slide-right"
                  data-sal-duration={800}
                >
                  <div
                    className="slick-slider slick-dot-nav featured-content"
                    data-slick='{"infinite": true,"arrows": false, "dots": true, "slidesToShow": 1, "asNavFor": ".featured-thumbnail"}'
                  >
                    <div className="slick-slide">
                      <div className="case-study-featured">
                        <div className="section-heading heading-left">
                          <span className="subtitle">Featured Case Study</span>
                          <h2 className="title">
                            Logo, identity &amp; web design for Uber
                          </h2>
                          <p>
                            Donec metus lorem, vulputate at sapien sit amet,
                            auctor iaculis lorem. In vel hendrerit nisi.
                            Vestibulum eget risus velit. Aliquam tristique
                            libero at dui sodales, et placerat orci lobortis.
                          </p>
                          <p>
                            Maecenas ipsum neque, elementum id dignissim et,
                            imperdiet vitae mauris.
                          </p>
                          <a
                            href="single-case-study.html"
                            className="axil-btn btn-fill-primary btn-large"
                          >
                            Read Case Study
                          </a>
                        </div>
                        <div className="case-study-counterup">
                          <div className="single-counterup">
                            <h2 className="count-number">
                              <span className="number count">15</span>
                              <span className="symbol">%</span>
                            </h2>
                            <span className="counter-title">ROI increase</span>
                          </div>
                          <div className="single-counterup">
                            <h2 className="count-number">
                              <span className="number count">60</span>
                              <span className="symbol">k</span>
                            </h2>
                            <span className="counter-title">
                              Monthly website visits
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="slick-slide">
                      <div className="case-study-featured">
                        <div className="section-heading heading-left">
                          <span className="subtitle">Featured Case Study</span>
                          <h2 className="title">
                            Website and web Development, Design
                          </h2>
                          <p>
                            Donec metus lorem, vulputate at sapien sit amet,
                            auctor iaculis lorem. In vel hendrerit nisi.
                            Vestibulum eget risus velit. Aliquam tristique
                            libero at dui sodales, et placerat orci lobortis.
                          </p>
                          <p>
                            Maecenas ipsum neque, elementum id dignissim et,
                            imperdiet vitae mauris.
                          </p>
                          <a
                            href="single-case-study.html"
                            className="axil-btn btn-fill-primary btn-large"
                          >
                            Read Case Study
                          </a>
                        </div>
                        <div className="case-study-counterup">
                          <div className="single-counterup">
                            <h2 className="count-number">
                              <span className="number count">15</span>
                              <span className="symbol">%</span>
                            </h2>
                            <span className="counter-title">ROI increase</span>
                          </div>
                          <div className="single-counterup">
                            <h2 className="count-number">
                              <span className="number count">60</span>
                              <span className="symbol">k</span>
                            </h2>
                            <span className="counter-title">
                              Monthly website visits
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="slick-slide">
                      <div className="case-study-featured">
                        <div className="section-heading heading-left">
                          <span className="subtitle">Featured Case Study</span>
                          <h2 className="title">
                            Branding, website &amp; digital marketing for Apple
                          </h2>
                          <p>
                            Donec metus lorem, vulputate at sapien sit amet,
                            auctor iaculis lorem. In vel hendrerit nisi.
                            Vestibulum eget risus velit. Aliquam tristique
                            libero at dui sodales, et placerat orci lobortis.
                          </p>
                          <p>
                            Maecenas ipsum neque, elementum id dignissim et,
                            imperdiet vitae mauris.
                          </p>
                          <a
                            href="single-case-study.html"
                            className="axil-btn btn-fill-primary btn-large"
                          >
                            Read Case Study
                          </a>
                        </div>
                        <div className="case-study-counterup">
                          <div className="single-counterup">
                            <h2 className="count-number">
                              <span className="number count">15</span>
                              <span className="symbol">%</span>
                            </h2>
                            <span className="counter-title">ROI increase</span>
                          </div>
                          <div className="single-counterup">
                            <h2 className="count-number">
                              <span className="number count">60</span>
                              <span className="symbol">k</span>
                            </h2>
                            <span className="counter-title">
                              Monthly website visits
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  className="col-xl-7 col-lg-6 d-none d-lg-block"
                  data-sal="slide-left"
                  data-sal-duration={800}
                >
                  <div
                    className="slick-slider slick-dot-nav featured-thumbnail"
                    data-slick='{"infinite": true,"arrows": false, "dots": false, "fade": true, "slidesToShow": 1, "asNavFor": ".featured-content"}'
                  >
                    <div className="slick-slide">
                      <div className="case-study-featured-thumb">
                        <img
                          src="assets/media/others/case-study-4.png"
                          alt="travel"
                        />
                      </div>
                    </div>
                    <div className="slick-slide">
                      <div className="case-study-featured-thumb">
                        <img
                          src="assets/media/others/case-study-5.png"
                          alt="travel"
                        />
                      </div>
                    </div>
                    <div className="slick-slide">
                      <div className="case-study-featured-thumb">
                        <img
                          src="assets/media/others/case-study-6.png"
                          alt="travel"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/*=====================================*/}
          {/*=        About Area Start         =*/}
          {/*=====================================*/}
          <section className="section section-padding-equal bg-color-light">
            <div className="container">
              <div className="row align-items-center">
                <div
                  className="col-lg-6"
                  data-sal="slide-up"
                  data-sal-duration={800}
                >
                  <div className="about-us">
                    <div className="section-heading heading-left mb-0">
                      <span className="subtitle">About Us</span>
                      <h2 className="title mb--40">
                        We do design, code &amp; develop.
                      </h2>
                      <p>
                        Nulla et velit gravida, facilisis quam a, molestie ante.
                        Mauris placerat suscipit dui, eget maximus tellus
                        blandit a. Praesent non tellus sed ligula commodo
                        blandit in et mauris. Quisque efficitur ipsum ut dolor
                        molestie pellentesque.{" "}
                      </p>
                      <p>
                        Nulla pharetra hendrerit mi quis dapibus. Quisque
                        luctus, tortor a venenatis fermentum, est lacus feugiat
                        nisl, id pharetra odio enim eget libero.{" "}
                      </p>
                    </div>
                  </div>
                </div>
                <div
                  className="col-xl-5 col-lg-6 offset-xl-1"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={100}
                >
                  <div className="contact-form-box">
                    <h3 className="title">Get a free Keystroke quote now</h3>
                    <form
                      method="POST"
                      action="mail.php"
                      className="axil-contact-form"
                    >
                      <div className="form-group">
                        <label>Name</label>
                        <input
                          type="text"
                          className="form-control"
                          name="contact-name"
                          placeholder="John Smith"
                        />
                      </div>
                      <div className="form-group">
                        <label>Email</label>
                        <input
                          type="email"
                          className="form-control"
                          name="contact-email"
                          placeholder="example@mail.com"
                        />
                      </div>
                      <div className="form-group mb--40">
                        <label>Phone</label>
                        <input
                          type="tel"
                          className="form-control"
                          name="contact-company"
                          placeholder={+123456789}
                        />
                      </div>
                      <div className="form-group">
                        <button
                          type="submit"
                          className="axil-btn btn-fill-primary btn-fluid btn-primary"
                          name="submit-btn"
                        >
                          Get Free Quote
                        </button>
                      </div>
                      <input
                        type="hidden"
                        className="form-control"
                        name="contact-message"
                        defaultValue="Null"
                      />
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <ul className="shape-group-6 list-unstyled">
              <li className="shape shape-1">
                <img src="assets/media/others/bubble-7.png" alt="Bubble" />
              </li>
              <li className="shape shape-2">
                <img src="assets/media/others/line-4.png" alt="line" />
              </li>
              <li className="shape shape-3">
                <img src="assets/media/others/line-5.png" alt="line" />
              </li>
            </ul>
          </section>
          {/*=====================================*/}
          {/*=        Project Area Start         =*/}
          {/*=====================================*/}
          <section className="section section-padding-2">
            <div className="container">
              <div className="section-heading heading-left mb--40">
                <span className="subtitle">Our Project</span>
                <h2 className="title">
                  Some of our <br /> finest work.
                </h2>
              </div>
              <div className="axil-isotope-wrapper">
                <div className="isotope-button isotope-project-btn">
                  <button data-filter="*" className="is-checked">
                    <span className="filter-text">All Works</span>
                  </button>
                  <button data-filter=".branding">
                    <span className="filter-text">Branding</span>
                  </button>
                  <button data-filter=".mobile">
                    <span className="filter-text">Mobile</span>
                  </button>
                </div>
                <div className="row row-35 isotope-list">
                  <div className="col-md-6 project branding">
                    <div className="project-grid">
                      <div className="thumbnail">
                        <a href="single-portfolio.html">
                          <img
                            src="assets/media/project/project-1.png"
                            alt="project"
                          />
                        </a>
                      </div>
                      <div className="content">
                        <h4 className="title">
                          <a href="single-portfolio.html">Creative Agency</a>
                        </h4>
                        <span className="subtitle">
                          Full Branding, Website, App
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-6 project mobile">
                    <div className="project-grid">
                      <div className="thumbnail">
                        <a href="single-portfolio.html">
                          <img
                            src="assets/media/project/project-2.png"
                            alt="project"
                          />
                        </a>
                      </div>
                      <div className="content">
                        <h4 className="title">
                          <a href="single-portfolio.html">Digital Marketing</a>
                        </h4>
                        <span className="subtitle">
                          Logo, Website &amp; Mobile App
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-6 project branding">
                    <div className="project-grid">
                      <div className="thumbnail">
                        <a href="single-portfolio.html">
                          <img
                            src="assets/media/project/project-3.png"
                            alt="project"
                          />
                        </a>
                      </div>
                      <div className="content">
                        <h4 className="title">
                          <a href="single-portfolio.html">Digital Agency</a>
                        </h4>
                        <span className="subtitle">Website, UI/UX</span>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-6 project mobile">
                    <div className="project-grid">
                      <div className="thumbnail">
                        <a href="single-portfolio.html">
                          <img
                            src="assets/media/project/project-4.png"
                            alt="project"
                          />
                        </a>
                      </div>
                      <div className="content">
                        <h4 className="title">
                          <a href="single-portfolio.html">Plan Management</a>
                        </h4>
                        <span className="subtitle">
                          Branding, Website, IOS App
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-6 project branding">
                    <div className="project-grid">
                      <div className="thumbnail">
                        <a href="single-portfolio.html">
                          <img
                            src="assets/media/project/project-5.png"
                            alt="project"
                          />
                        </a>
                      </div>
                      <div className="content">
                        <h4 className="title">
                          <a href="single-portfolio.html">Social Engagement</a>
                        </h4>
                        <span className="subtitle">Design, Development</span>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-6 project mobile">
                    <div className="project-grid">
                      <div className="thumbnail">
                        <a href="single-portfolio.html">
                          <img
                            src="assets/media/project/project-6.png"
                            alt="project"
                          />
                        </a>
                      </div>
                      <div className="content">
                        <h4 className="title">
                          <a href="single-portfolio.html">Web Application</a>
                        </h4>
                        <span className="subtitle">Logo, Webapp, App</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <ul className="shape-group-7 list-unstyled">
              <li className="shape shape-1">
                <img src="assets/media/others/circle-2.png" alt="circle" />
              </li>
              <li className="shape shape-2">
                <img src="assets/media/others/bubble-2.png" alt="Line" />
              </li>
              <li className="shape shape-3">
                <img src="assets/media/others/bubble-1.png" alt="Line" />
              </li>
            </ul>
          </section>
          {/*=====================================*/}
          {/*=        Counter Up Area Start      =*/}
          {/*=====================================*/}
          <section className="section section-padding bg-color-dark">
            <div className="container">
              <div className="section-heading heading-light">
                <span className="subtitle">Featured Case Study</span>
                <h2 className="title">Design startup movement</h2>
                <p>
                  In vel varius turpis, non dictum sem. Aenean in efficitur
                  ipsum, in egestas ipsum. Mauris in mi ac tellus.
                </p>
              </div>
              <div className="row">
                <div
                  className="col-lg-3 col-6"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={100}
                >
                  <div className="counterup-progress active">
                    <div className="icon">
                      <img src="assets/media/icon/icon-7.png" alt="Apple" />
                    </div>
                    <div className="count-number h2">
                      <span className="number count">15</span>
                      <span className="symbol">+</span>
                    </div>
                    <h6 className="title">Years of operation</h6>
                  </div>
                </div>
                <div
                  className="col-lg-3 col-6"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={200}
                >
                  <div className="counterup-progress">
                    <div className="icon">
                      <img src="assets/media/icon/icon-8.png" alt="Apple" />
                    </div>
                    <div className="count-number h2">
                      <span className="number count">360</span>
                      <span className="symbol">+</span>
                    </div>
                    <h6 className="title">Projects deliverd</h6>
                  </div>
                </div>
                <div
                  className="col-lg-3 col-6"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={300}
                >
                  <div className="counterup-progress">
                    <div className="icon">
                      <img src="assets/media/icon/icon-9.png" alt="Apple" />
                    </div>
                    <div className="count-number h2">
                      <span className="number count">600</span>
                      <span className="symbol">+</span>
                    </div>
                    <h6 className="title">Specialist</h6>
                  </div>
                </div>
                <div
                  className="col-lg-3 col-6"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={400}
                >
                  <div className="counterup-progress">
                    <div className="icon">
                      <img src="assets/media/icon/apple.png" alt="Apple" />
                    </div>
                    <div className="count-number h2">
                      <span className="number count">64</span>
                      <span className="symbol">+</span>
                    </div>
                    <h6 className="title">Years of operation</h6>
                  </div>
                </div>
              </div>
            </div>
            <ul className="shape-group-5 list-unstyled">
              <li className="shape shape-1">
                <img src="assets/media/others/circle-1.png" alt="line" />
              </li>
              <li className="shape shape-2">
                <img src="assets/media/others/line-3.png" alt="line" />
              </li>
              <li className="shape shape-3">
                <img src="assets/media/others/bubble-5.png" alt="line" />
              </li>
              <li className="shape shape-4">
                <img src="assets/media/others/bubble-6.png" alt="line" />
              </li>
            </ul>
          </section>
          {/*=====================================*/}
          {/*=        Testimonial Area Start      =*/}
          {/*=====================================*/}
          <section className="section section-padding">
            <div className="container">
              <div className="section-heading heading-left">
                <span className="subtitle">Testimonial</span>
                <h2 className="title">From getting started</h2>
                <p>
                  Nulla facilisi. Nullam in magna id dolor blandit rutrum eget
                  vulputate augue sed eu leo eget risus imperdiet.
                </p>
              </div>
              <div className="row">
                <div
                  className="col-lg-4"
                  data-sal="slide-up"
                  data-sal-duration={1000}
                  data-sal-delay={100}
                >
                  <div className="testimonial-grid active">
                    <span className="social-media">
                      <img src="assets/media/icon/yelp-2.png" alt="Yelp" />
                    </span>
                    <p>
                      “ Donec metus lorem, vulputate at sapien sit amet, auctor
                      iaculis lorem. In vel hendrerit nisi. Vestibulum eget
                      risus velit. ”
                    </p>
                    <div className="author-info">
                      <div className="thumb">
                        <img
                          src="assets/media/testimonial/testimonial-1.png"
                          alt="Google Review"
                        />
                      </div>
                      <div className="content">
                        <span className="name">Darrell Steward</span>
                        <span className="designation">Executive Chairman</span>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  className="col-lg-4"
                  data-sal="slide-up"
                  data-sal-duration={1000}
                  data-sal-delay={200}
                >
                  <div className="testimonial-grid">
                    <span className="social-media">
                      <img src="assets/media/icon/google-2.png" alt="google" />
                    </span>
                    <p>
                      “ Donec metus lorem, vulputate at sapien sit amet, auctor
                      iaculis lorem. In vel hendrerit nisi. Vestibulum eget
                      risus velit. ”
                    </p>
                    <div className="author-info">
                      <div className="thumb">
                        <img
                          src="assets/media/testimonial/testimonial-2.png"
                          alt="Google Review"
                        />
                      </div>
                      <div className="content">
                        <span className="name">Savannah Nguyen</span>
                        <span className="designation">Executive Chairman</span>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  className="col-lg-4"
                  data-sal="slide-up"
                  data-sal-duration={1000}
                  data-sal-delay={300}
                >
                  <div className="testimonial-grid">
                    <span className="social-media">
                      <img src="assets/media/icon/fb-2.png" alt="Facebook" />
                    </span>
                    <p>
                      “ Donec metus lorem, vulputate at sapien sit amet, auctor
                      iaculis lorem. In vel hendrerit nisi. Vestibulum eget
                      risus velit. ”
                    </p>
                    <div className="author-info">
                      <div className="thumb">
                        <img
                          src="assets/media/testimonial/testimonial-3.png"
                          alt="Google Review"
                        />
                      </div>
                      <div className="content">
                        <span className="name">Floyd Miles</span>
                        <span className="designation">Executive Chairman</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <ul className="shape-group-4 list-unstyled">
              <li className="shape-1">
                <img src="assets/media/others/bubble-1.png" alt="Bubble" />
              </li>
            </ul>
          </section>
          {/*=====================================*/}
          {/*=        Pricing Area Start       	=*/}
          {/*=====================================*/}
          <section className="section bg-color-light section-padding">
            <div className="container">
              <div className="section-heading mb-0">
                <span className="subtitle">Pricing Plan</span>
                <h2 className="title">Find the Right Plan.</h2>
                <p>
                  Flexible pricing options for freelancers <br /> and design
                  teams.
                </p>
              </div>
              <div className="pricing-billing-duration">
                <ul>
                  <li className="nav-item">
                    <button
                      className="nav-link active"
                      id="yearly-plan-btn"
                      type="button"
                    >
                      Billed yearly
                    </button>
                  </li>
                  <li className="nav-item billed-check-box">
                    <input type="checkbox" id="pricing-checkbox" />
                    <label htmlFor="pricing-checkbox" />
                  </li>
                  <li className="nav-item">
                    <button
                      className="nav-link"
                      id="monthly-plan-btn"
                      type="button"
                    >
                      Billed monthly
                    </button>
                  </li>
                </ul>
              </div>
              <div className="row">
                <div
                  className="col-lg-4"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={100}
                >
                  <div className="pricing-table active">
                    <div className="star-icon">
                      <i className="fas fa-star" />
                    </div>
                    <div className="pricing-header">
                      <h3 className="title">Professional</h3>
                      <span className="subtitle">
                        A beautiful, simple website
                      </span>
                      <div className="price-wrap">
                        <div className="yearly-pricing">
                          <span className="amount">$119.99</span>
                          <span className="duration">/yearly</span>
                        </div>
                        <div className="monthly-pricing">
                          <span className="amount">$19.00</span>
                          <span className="duration">/monthly</span>
                        </div>
                      </div>
                      <div className="pricing-btn">
                        <a
                          href="#"
                          className="axil-btn btn-large-fluid btn-borderd"
                        >
                          Get Started Today
                        </a>
                      </div>
                    </div>
                    <div className="pricing-body">
                      <ul className="list-unstyled">
                        <li>10 Pages Responsive Website</li>
                        <li>5 PPC Campaigns</li>
                        <li>10 SEO Keywords</li>
                        <li>5 Facebook Camplaigns</li>
                        <li>2 Video Camplaigns</li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div
                  className="col-lg-4"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={200}
                >
                  <div className="pricing-table">
                    <div className="pricing-header">
                      <h3 className="title">Standard</h3>
                      <span className="subtitle">Small Team</span>
                      <div className="price-wrap">
                        <div className="yearly-pricing">
                          <span className="amount">$219.99</span>
                          <span className="duration">/yearly</span>
                        </div>
                        <div className="monthly-pricing">
                          <span className="amount">$29.00</span>
                          <span className="duration">/monthly</span>
                        </div>
                      </div>
                      <div className="pricing-btn">
                        <a
                          href="#"
                          className="axil-btn btn-large-fluid btn-borderd"
                        >
                          Get Started Today
                        </a>
                      </div>
                    </div>
                    <div className="pricing-body">
                      <ul className="list-unstyled">
                        <li>50 Pages Responsive Website</li>
                        <li>Unlimited PPC Campaigns</li>
                        <li>Unlimited SEO Keywords</li>
                        <li>Unlimited Facebook Camplaigns</li>
                        <li>Unlimited Video Camplaigns</li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div
                  className="col-lg-4"
                  data-sal="slide-up"
                  data-sal-duration={800}
                  data-sal-delay={300}
                >
                  <div className="pricing-table">
                    <div className="pricing-header">
                      <h3 className="title">Ultimate</h3>
                      <span className="subtitle">Large Team</span>
                      <div className="price-wrap">
                        <div className="yearly-pricing">
                          <span className="amount">$559.99</span>
                          <span className="duration">/yearly</span>
                        </div>
                        <div className="monthly-pricing">
                          <span className="amount">$59.00</span>
                          <span className="duration">/monthly</span>
                        </div>
                      </div>
                      <div className="pricing-btn">
                        <a
                          href="#"
                          className="axil-btn btn-large-fluid btn-borderd"
                        >
                          Get Started Today
                        </a>
                      </div>
                    </div>
                    <div className="pricing-body">
                      <ul className="list-unstyled">
                        <li>10 Pages Responsive Website</li>
                        <li>5 PPC Campaigns</li>
                        <li>10 SEO Keywords</li>
                        <li>5 Facebook Camplaigns</li>
                        <li>2 Video Camplaigns</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <ul className="shape-group-3 list-unstyled">
              <li className="shape shape-1">
                <img src="assets/media/others/line-1.png" alt="shape" />
              </li>
              <li className="shape shape-2">
                <img src="assets/media/others/bubble-4.png" alt="shape" />
              </li>
              <li className="shape shape-3">
                <img src="assets/media/others/hand-1.png" alt="shape" />
              </li>
            </ul>
          </section>
          {/*=====================================*/}
          {/*=        Brand Area Start       	=*/}
          {/*=====================================*/}
          <section className="section section-padding bg-color-dark">
            <div className="container">
              <div className="section-heading heading-light-left">
                <span className="subtitle">Top Clients</span>
                <h2 className="title">We’ve built solutions for...</h2>
                <p>
                  Design anything from simple icons to fully featured websites
                  and applications.
                </p>
              </div>
              <div className="row">
                <div
                  className="col-lg-3 col-6"
                  data-sal="slide-up"
                  data-sal-duration={500}
                >
                  <div className="brand-grid active">
                    <img src="assets/media/brand/brand-1.png" alt="Brand" />
                  </div>
                </div>
                <div
                  className="col-lg-3 col-6"
                  data-sal="slide-up"
                  data-sal-duration={500}
                  data-sal-delay={100}
                >
                  <div className="brand-grid">
                    <img src="assets/media/brand/brand-2.png" alt="Brand" />
                  </div>
                </div>
                <div
                  className="col-lg-3 col-6"
                  data-sal="slide-up"
                  data-sal-duration={500}
                  data-sal-delay={200}
                >
                  <div className="brand-grid">
                    <img src="assets/media/brand/brand-3.png" alt="Brand" />
                  </div>
                </div>
                <div
                  className="col-lg-3 col-6"
                  data-sal="slide-up"
                  data-sal-duration={500}
                  data-sal-delay={300}
                >
                  <div className="brand-grid">
                    <img src="assets/media/brand/brand-4.png" alt="Brand" />
                  </div>
                </div>
                <div
                  className="col-lg-3 col-6"
                  data-sal="slide-up"
                  data-sal-duration={500}
                  data-sal-delay={400}
                >
                  <div className="brand-grid">
                    <img src="assets/media/brand/brand-5.png" alt="Brand" />
                  </div>
                </div>
                <div
                  className="col-lg-3 col-6"
                  data-sal="slide-up"
                  data-sal-duration={500}
                  data-sal-delay={500}
                >
                  <div className="brand-grid">
                    <img src="assets/media/brand/brand-6.png" alt="Brand" />
                  </div>
                </div>
                <div
                  className="col-lg-3 col-6"
                  data-sal="slide-up"
                  data-sal-duration={500}
                  data-sal-delay={600}
                >
                  <div className="brand-grid">
                    <img src="assets/media/brand/brand-7.png" alt="Brand" />
                  </div>
                </div>
                <div
                  className="col-lg-3 col-6"
                  data-sal="slide-up"
                  data-sal-duration={500}
                  data-sal-delay={700}
                >
                  <div className="brand-grid">
                    <img src="assets/media/brand/brand-8.png" alt="Brand" />
                  </div>
                </div>
              </div>
            </div>
            <ul className="shape-group-2 list-unstyled">
              <li className="shape shape-1">
                <img src="assets/media/others/circle-1.png" alt="circle" />
              </li>
              <li className="shape shape-2">
                <img src="assets/media/others/line-3.png" alt="circle" />
              </li>
              <li className="shape shape-3">
                <img src="assets/media/others/bubble-3.png" alt="circle" />
              </li>
            </ul>
          </section>
          {/*=====================================*/}
          {/*=        Blog Area Start       	    =*/}
          {/*=====================================*/}
          <section className="section section-padding-equal">
            <div className="container">
              <div className="section-heading">
                <span className="subtitle">What's Going On</span>
                <h2 className="title">Latest stories</h2>
                <p>
                  News From Abstrak And Around The World Of Web Design And
                  Complete Solution of Online Digital Marketing{" "}
                </p>
              </div>
              <div className="row g-0">
                <div
                  className="col-xl-6"
                  data-sal="slide-right"
                  data-sal-duration={800}
                  data-sal-delay={100}
                >
                  <div className="blog-list active">
                    <div className="post-thumbnail">
                      <a href="single-blog-2.html">
                        <img
                          src="assets/media/blog/blog-1.png"
                          alt="Blog Post"
                        />
                      </a>
                    </div>
                    <div className="post-content">
                      <h5 className="title">
                        <a href="single-blog-2.html">
                          How To Use a Remarketing Strategy To Get More
                        </a>
                      </h5>
                      <p>
                        Demand generation is a constant struggle for any
                        business. Each marketing strategy you employ has...
                      </p>
                      <a href="single-blog-2.html" className="more-btn">
                        Learn more
                        <i className="far fa-angle-right" />
                      </a>
                    </div>
                  </div>
                </div>
                <div
                  className="col-xl-6"
                  data-sal="slide-left"
                  data-sal-duration={800}
                  data-sal-delay={100}
                >
                  <div className="blog-list border-start">
                    <div className="post-thumbnail">
                      <a href="single-blog-3.html">
                        <img
                          src="assets/media/blog/blog-2.png"
                          alt="Blog Post"
                        />
                      </a>
                    </div>
                    <div className="post-content">
                      <h5 className="title">
                        <a href="single-blog-3.html">
                          SEO Statistics You Should Know in 2021
                        </a>
                      </h5>
                      <p>
                        Organic search has the potential to capture more than 40
                        percent of your gross revenue...
                      </p>
                      <a href="single-blog-3.html" className="more-btn">
                        Learn more
                        <i className="far fa-angle-right" />
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <ul className="shape-group-1 list-unstyled">
              <li className="shape shape-1">
                <img src="assets/media/others/bubble-1.png" alt="bubble" />
              </li>
              <li className="shape shape-2">
                <img src="assets/media/others/line-1.png" alt="bubble" />
              </li>
              <li className="shape shape-3">
                <img src="assets/media/others/line-2.png" alt="bubble" />
              </li>
              <li className="shape shape-4">
                <img src="assets/media/others/bubble-2.png" alt="bubble" />
              </li>
            </ul>
          </section>
          {/*=====================================*/}
          {/*=     Call To Action Area Start     =*/}
          {/*=====================================*/}
          <section className="section call-to-action-area">
            <div className="container">
              <div className="call-to-action">
                <div className="section-heading heading-light">
                  <span className="subtitle">Let's Work Together</span>
                  <h2 className="title">Need a successful project?</h2>
                  <a
                    href="contact.html"
                    className="axil-btn btn-large btn-fill-white"
                  >
                    Estimate Project
                  </a>
                </div>
                <div className="thumbnail">
                  <div
                    className="larg-thumb"
                    data-sal="zoom-in"
                    data-sal-duration={600}
                    data-sal-delay={100}
                  >
                    <img src="assets/media/others/pc.png" alt="Computer" />
                  </div>
                  <ul className="list-unstyled small-thumb">
                    <li
                      className="shape shape-1"
                      data-sal="slide-right"
                      data-sal-duration={800}
                      data-sal-delay={400}
                    >
                      <img
                        src="assets/media/others/comment.png"
                        alt="Comments"
                      />
                    </li>
                    <li
                      className="shape shape-2"
                      data-sal="slide-up"
                      data-sal-duration={800}
                      data-sal-delay={300}
                    >
                      <img
                        src="assets/media/others/keyboard.png"
                        alt="Comments"
                      />
                    </li>
                    <li
                      className="shape shape-3"
                      data-sal="slide-right"
                      data-sal-duration={800}
                      data-sal-delay={300}
                    >
                      <img src="assets/media/others/mouse.png" alt="Comments" />
                    </li>
                    <li
                      className="shape shape-4"
                      data-sal="slide-left"
                      data-sal-duration={800}
                      data-sal-delay={300}
                    >
                      <img
                        src="assets/media/others/bell-icon.png"
                        alt="Comments"
                      />
                    </li>
                    <li
                      className="shape shape-5"
                      data-sal="zoom-in"
                      data-sal-duration={800}
                      data-sal-delay={200}
                    >
                      <img
                        src="assets/media/others/chat-bot.png"
                        alt="Comments"
                      />
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <ul className="list-unstyled shape-group-9">
              <li className="shape shape-1">
                <img src="assets/media/others/bubble-12.png" alt="Comments" />
              </li>
              <li className="shape shape-2">
                <img src="assets/media/others/bubble-16.png" alt="Comments" />
              </li>
              <li className="shape shape-3">
                <img src="assets/media/others/bubble-13.png" alt="Comments" />
              </li>
              <li className="shape shape-4">
                <img src="assets/media/others/bubble-14.png" alt="Comments" />
              </li>
              <li className="shape shape-5">
                <img src="assets/media/others/bubble-16.png" alt="Comments" />
              </li>
              <li className="shape shape-6">
                <img src="assets/media/others/bubble-15.png" alt="Comments" />
              </li>
              <li className="shape shape-7">
                <img src="assets/media/others/bubble-16.png" alt="Comments" />
              </li>
            </ul>
          </section>
          {/*=====================================*/}
          {/*=        Footer Area Start       	=*/}
          {/*=====================================*/}
          <footer className="footer-area">
            <div className="container">
              <div className="footer-top">
                <div className="footer-social-link">
                  <ul className="list-unstyled">
                    <li>
                      <a
                        href="../../../index.htm"
                        data-sal="slide-up"
                        data-sal-duration={500}
                        data-sal-delay={100}
                      >
                        <i className="fab fa-facebook-f" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="../../../index-1.htm"
                        data-sal="slide-up"
                        data-sal-duration={500}
                        data-sal-delay={200}
                      >
                        <i className="fab fa-twitter" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="../../../index-2.htm"
                        data-sal="slide-up"
                        data-sal-duration={500}
                        data-sal-delay={300}
                      >
                        <i className="fab fa-pinterest-p" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="../../../index-3.htm"
                        data-sal="slide-up"
                        data-sal-duration={500}
                        data-sal-delay={400}
                      >
                        <i className="fab fa-linkedin-in" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="../../../index-4.htm"
                        data-sal="slide-up"
                        data-sal-duration={500}
                        data-sal-delay={500}
                      >
                        <i className="fab fa-instagram" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="../../../index-5.htm"
                        data-sal="slide-up"
                        data-sal-duration={500}
                        data-sal-delay={600}
                      >
                        <i className="fab fa-vimeo-v" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="../../../index-6.htm"
                        data-sal="slide-up"
                        data-sal-duration={500}
                        data-sal-delay={700}
                      >
                        <i className="fab fa-dribbble" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="../../../index-7.htm"
                        data-sal="slide-up"
                        data-sal-duration={500}
                        data-sal-delay={800}
                      >
                        <i className="fab fa-behance" />
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
              <div className="footer-main">
                <div className="row">
                  <div
                    className="col-xl-6 col-lg-5"
                    data-sal="slide-right"
                    data-sal-duration={800}
                    data-sal-delay={100}
                  >
                    <div className="footer-widget border-end">
                      <div className="footer-newsletter">
                        <h2 className="title">Get in touch!</h2>
                        <p>
                          Fusce varius, dolor tempor interdum tristique, dui
                          urna bib endum magna, ut ullamcorper purus
                        </p>
                        <form>
                          <div className="input-group">
                            <input
                              type="email"
                              className="form-control"
                              placeholder="Email address"
                            />
                            <button className="subscribe-btn" type="submit">
                              Subscribe
                            </button>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                  <div
                    className="col-xl-6 col-lg-7"
                    data-sal="slide-left"
                    data-sal-duration={800}
                    data-sal-delay={100}
                  >
                    <div className="row">
                      <div className="col-sm-6">
                        <div className="footer-widget">
                          <h6 className="widget-title">Services</h6>
                          <div className="footer-menu-link">
                            <ul className="list-unstyled">
                              <li>
                                <a href="service-design.html">
                                  Logo &amp; Branding
                                </a>
                              </li>
                              <li>
                                <a href="service-development.html">
                                  Website Development
                                </a>
                              </li>
                              <li>
                                <a href="service-development.html">
                                  Mobile App Development
                                </a>
                              </li>
                              <li>
                                <a href="service-marketing.html">
                                  Search Engine Optimization
                                </a>
                              </li>
                              <li>
                                <a href="service-marketing.html">
                                  Pay-Per-Click
                                </a>
                              </li>
                              <li>
                                <a href="service-marketing.html">
                                  Social Media Marketing
                                </a>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                      <div className="col-sm-3">
                        <div className="footer-widget">
                          <h6 className="widget-title">Resourses</h6>
                          <div className="footer-menu-link">
                            <ul className="list-unstyled">
                              <li>
                                <a href="blog.html">Blog</a>
                              </li>
                              <li>
                                <a href="case-study.html">Case Studies</a>
                              </li>
                              <li>
                                <a href="project.html">Portfolio</a>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                      <div className="col-sm-3">
                        <div className="footer-widget">
                          <h6 className="widget-title">Support</h6>
                          <div className="footer-menu-link">
                            <ul className="list-unstyled">
                              <li>
                                <a href="contact.html">Contact</a>
                              </li>
                              <li>
                                <a href="privacy-policy.html">Privacy Policy</a>
                              </li>
                              <li>
                                <a href="terms-of-use.html">Terms of Use</a>
                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                className="footer-bottom"
                data-sal="slide-up"
                data-sal-duration={500}
                data-sal-delay={100}
              >
                <div className="row">
                  <div className="col-md-6">
                    <div className="footer-copyright">
                      <span className="copyright-text">
                        © 2021. All rights reserved by{" "}
                        <a href="https://axilthemes.com/">Axilthemes</a>.
                      </span>
                    </div>
                  </div>
                  <div className="col-md-6">
                    <div className="footer-bottom-link">
                      <ul className="list-unstyled">
                        <li>
                          <a href="privacy-policy.html">Privacy Policy</a>
                        </li>
                        <li>
                          <a href="terms-of-use.html">Terms of Use</a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </footer>
          {/*=====================================*/}
          {/*=       Offcanvas Menu Area       	=*/}
          {/*=====================================*/}
          <div
            className="offcanvas offcanvas-end header-offcanvasmenu"
            tabIndex={-1}
            id="offcanvasMenuRight"
          >
            <div className="offcanvas-header">
              <button
                type="button"
                className="btn-close"
                data-bs-dismiss="offcanvas"
                aria-label="Close"
              />
            </div>
            <div className="offcanvas-body">
              <form action="#" className="side-nav-search-form">
                <div className="form-group">
                  <input
                    type="text"
                    className="search-field"
                    name="search-field"
                    placeholder="Search..."
                  />
                  <button className="side-nav-search-btn">
                    <i className="fas fa-search" />
                  </button>
                </div>
              </form>
              <div className="row ">
                <div className="col-lg-5 col-xl-6">
                  <ul className="main-navigation list-unstyled">
                    <li>
                      <a href="index-1.html">Digital Agency</a>
                    </li>
                    <li>
                      <a href="index-2.html">Creative Agency</a>
                    </li>
                    <li>
                      <a href="index-3.html">Personal Portfolio</a>
                    </li>
                    <li>
                      <a href="index-4.html">Home Startup</a>
                    </li>
                    <li>
                      <a href="index-5.html">Corporate Agency</a>
                    </li>
                  </ul>
                </div>
                <div className="col-lg-7 col-xl-6">
                  <div className="contact-info-wrap">
                    <div className="contact-inner">
                      <address className="address">
                        <span className="title">Contact Information</span>
                        <p>
                          Theodore Lowe, Ap #867-859 <br /> Sit Rd, Azusa New
                          York
                        </p>
                      </address>
                      <address className="address">
                        <span className="title">
                          We're Available 24/7. Call Now.
                        </span>
                        <a className="tel" href="tel:8884562790">
                          <i className="fas fa-phone" />
                          (888) 456-2790
                        </a>
                        <a className="tel" href="tel:12125553333">
                          <i className="fas fa-fax" />
                          (121) 255-53333
                        </a>
                      </address>
                    </div>
                    <div className="contact-inner">
                      <h5 className="title">Find us here</h5>
                      <div className="contact-social-share">
                        <ul className="social-share list-unstyled">
                          <li>
                            <a href="../../../index.htm">
                              <i className="fab fa-facebook-f" />
                            </a>
                          </li>
                          <li>
                            <a href="../../../index-1.htm">
                              <i className="fab fa-twitter" />
                            </a>
                          </li>
                          <li>
                            <a href="../../../index-7.htm">
                              <i className="fab fa-behance" />
                            </a>
                          </li>
                          <li>
                            <a href="../../../index-3.htm">
                              <i className="fab fa-linkedin-in" />
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </>
    </>
  );
}
